## Handling Imbalanced Dataset

1. Up Sampling
2. Down Sampling

In [1]:
import numpy as np
import pandas as pd

# Set the random seed for reproducibility
np.random.seed(123)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [2]:
n_class_0,n_class_1

(900, 100)

In [1]:
import numpy as np
a=np.random.normal(loc=0, scale=1, size=1000)
a

array([ 6.78353866e-01,  8.59802678e-01,  1.25622255e+00,  1.05677399e+00,
        1.08215019e+00,  1.31914045e+00, -1.01301166e-02,  1.89151343e-01,
        2.76436671e+00,  3.76439710e-02,  1.03325694e+00, -2.33384170e+00,
        1.47644656e+00, -2.94372253e+00, -1.03612959e+00, -1.18376110e+00,
       -7.14568317e-02,  3.66197470e-01,  3.66950934e-01, -6.49109632e-01,
       -1.12857491e+00, -1.47671644e-01, -2.21014998e-01, -2.74288287e-01,
        7.45714287e-01,  5.56218275e-01, -3.43085934e-01, -1.59413343e-01,
       -1.51852759e+00, -2.31766414e-01,  8.78689419e-01, -5.62474999e-02,
       -1.30422035e+00, -3.36008707e-01,  1.85589548e+00, -1.32799233e+00,
       -1.89324180e+00, -8.06645446e-01,  2.03162700e-01, -5.62693314e-01,
        2.19215500e-01,  3.80926665e-01,  1.65315448e+00, -6.02970714e-01,
        2.21921729e+00,  7.12302217e-01,  1.91454521e+00, -9.72069585e-02,
        8.45752258e-01, -4.26726336e-01,  1.48958685e+00,  1.51286889e+00,
       -1.37595844e+00,  4.62314948e-01, -2.23587286e+00, -9.48384685e-01,
        8.30257088e-01,  4.37257475e-01, -6.59194284e-01, -3.99224978e-01,
       -1.43917729e+00, -9.25634825e-01,  1.09746497e+00,  1.46983831e-01,
        4.94145434e-01, -3.70110092e-01, -6.89625681e-01,  4.83385593e-01,
       -4.78447144e-01, -2.18089779e+00,  1.96823020e+00, -1.47154174e+00,
        2.74120233e-01,  1.57573064e-01,  6.09229646e-01, -5.18614202e-01,
       -1.06162704e-01, -2.27442667e+00,  8.43649308e-01,  4.24505155e-02,
       -3.69345744e-01,  4.20389266e-01, -1.21540173e+00, -1.51607863e+00,
       -8.09126469e-01,  4.25146144e-01,  1.38673881e+00,  1.26768277e+00,
        1.06107188e+00, -9.71605007e-01, -2.29792394e-01,  9.73048332e-01,
       -1.55504287e+00, -3.11876040e-01,  1.99594325e-01, -8.94177931e-01,
        4.64833622e-02, -1.22146713e+00,  8.80747934e-02, -6.79415283e-01,
       -1.42119476e+00, -8.48680381e-01,  1.91740787e-01,  6.59423607e-01,
       -4.86260390e-02, -5.11865859e-01, -1.49573509e-02, -6.24402909e-01,
       -1.27907677e+00, -1.62344880e+00,  7.52326729e-01,  5.09640752e-01,
       -1.28733391e+00,  6.41664803e-01, -1.25561282e+00, -1.05023619e+00,
       -1.61364369e+00,  3.50772577e-01, -1.22812946e-02, -3.21721404e-01,
        7.89987878e-01,  6.10799942e-01, -6.71112238e-01, -7.99438269e-01,
       -1.21183712e+00, -5.26794070e-01, -9.39033850e-01,  3.94994469e-01,
        9.12256045e-01, -1.63404537e+00,  7.86727285e-02,  3.81700113e-01,
       -1.11583722e+00, -3.83649289e-01,  4.57769343e-01, -1.12896242e+00,
        1.76158345e-01, -3.19937603e-01, -8.92387605e-01,  6.88374245e-01,
        6.07959459e-01, -1.11314513e-01, -4.41139623e-03,  1.66087970e+00,
        8.40153003e-01,  1.32083421e+00,  2.24802704e-01, -1.24333781e+00,
        4.07171524e-01,  4.21893163e-01,  2.60231593e-01, -2.38449617e-01,
        2.59043236e-01,  3.99488713e-01, -1.12717843e+00, -9.37830947e-01,
       -2.37917155e-01,  6.67288714e-01, -2.95431879e-01,  3.21821205e-01,
       -6.36649399e-01,  8.50419918e-01,  1.62181604e-01, -7.32123970e-01,
        4.94349633e-01,  6.11888914e-02, -3.59577186e-01, -4.66832070e-02,
        5.39705024e-02,  6.13371682e-01,  1.35062089e+00, -1.94306744e+00,
       -8.11014311e-01, -1.64223448e+00, -1.19958201e+00, -1.26573241e+00,
       -1.38819341e+00, -3.76064474e+00, -9.69629265e-01,  9.06970521e-01,
       -2.14665297e-01, -9.05552542e-01, -2.13723189e-01,  2.45653285e-01,
        1.23548341e+00, -9.20436897e-01,  2.24480152e-01,  5.61253549e-01,
       -8.73912147e-01, -3.77291769e-01, -2.92195236e-01, -1.08133921e+00,
       -2.59985251e+00,  1.15324110e+00, -3.70402969e-01, -1.10768549e+00,
        1.76402994e+00,  2.84279357e-01,  1.86532585e+00,  5.50454425e-01,
       -1.47014211e+00,  3.17441165e-01,  3.69865849e-03, -1.13503289e-01,
       -2.54128932e+00,  2.50748346e+00,  6.49619915e-01,  2.18149688e+00,
        5.21323882e-01,  1.80776518e-02, -8.82485817e-01,  4.25430576e-01,
       -1.27947034e+00,  5.24980214e-01,  6.41865835e-01, -8.00217066e-01,
        4.26327361e-01, -9.29825505e-02, -1.93399211e-01,  2.06525748e-01,
        4.52063297e-01,  5.05768691e-01,  1.99082831e-01,  7.21823192e-01,
       -1.61714694e+00, -1.02847620e+00,  3.03201971e-01,  1.08047972e+00,
        7.79631013e-01, -1.43306308e+00,  7.70103349e-01, -6.08928777e-01,
        3.30090870e-01, -1.27895485e+00,  1.48687683e+00,  8.23340641e-01,
        7.86130875e-01,  8.61099531e-01, -1.50494043e-01,  4.62355567e-01,
       -5.36396303e-01,  2.10912704e+00,  3.28758604e-01,  7.00400572e-01,
        1.50600225e+00, -9.18042364e-01, -7.08918032e-01, -2.36311208e-01,
        9.45292741e-02, -1.64860123e+00,  5.24103544e-01,  2.30311368e-01,
       -9.34581212e-01,  6.64909846e-02,  2.41503875e-01, -4.72851360e-01,
        1.06311980e-01,  2.80161742e-02, -5.51690243e-01, -6.95815305e-02,
       -1.28146834e+00,  4.32148483e-01, -3.00581124e-01,  4.72810160e-01,
        3.36448860e-02,  4.02023845e-01, -6.42070983e-01, -2.30024496e-01,
        1.23627623e+00,  3.54382119e-01, -2.52389003e+00,  1.12888355e+00,
       -3.38665861e-01, -2.03750428e-02, -1.72109008e-01,  1.93897842e-01,
       -3.50651186e-01,  6.45961642e-01, -5.23006880e-01, -1.45739122e+00,
       -5.27422964e-01,  9.83745328e-01,  1.10538796e-02,  1.82446655e+00,
        2.61223363e+00,  2.73978554e-01, -7.08015226e-01,  5.79933905e-01,
       -7.67766074e-01, -1.67319338e+00, -1.51229261e+00, -7.22873347e-01,
       -1.92438570e-01,  2.17183611e-02,  4.90505383e-02,  1.00310347e+00,
        4.79548493e-01,  1.51711896e+00,  3.53278981e+00,  1.05565251e+00,
        1.12585903e+00,  2.21667716e+00, -6.62871275e-01,  1.54826612e-01,
       -1.61192714e-01, -1.62395734e+00,  3.87749911e-01, -7.04206992e-02,
        5.26080192e-01, -1.60184635e+00, -1.04690566e+00, -2.23669488e-01,
       -9.40416461e-01, -7.60073197e-01, -2.36589933e-01,  3.65779172e-01,
       -1.11051484e+00, -2.50763453e-01, -1.23359476e+00,  1.31660160e-01,
        4.83493424e-01, -2.62293581e-01,  8.64916446e-01, -8.58646155e-01,
       -5.37064789e-01,  1.90009305e+00, -3.13928964e-01, -3.82041429e-01,
        8.32347479e-01, -2.57556619e-01,  1.52764294e+00,  1.28721518e+00,
       -4.78863818e-01, -7.13477382e-01, -4.92617632e-01,  9.52976017e-02,
        6.87640709e-01, -4.33049952e-01,  9.01028071e-01,  1.37415875e-01,
        1.48349092e+00, -3.42996298e-01,  9.63503645e-01, -2.67573042e-01,
       -9.77220751e-01,  1.97996201e-01, -8.45859329e-01,  9.02208475e-01,
       -1.90299994e-01,  5.71207694e-01,  2.55130927e-01,  3.88291254e-01,
       -1.15658189e+00,  5.76614968e-01,  1.26921818e+00, -1.83827341e+00,
        7.96453498e-01,  7.28303734e-01, -3.61144985e-01, -6.56374855e-01,
       -1.12769699e+00, -1.37544451e+00, -5.47783987e-01,  7.61521269e-01,
        2.33880860e+00, -7.15445293e-01,  2.46011997e-01, -2.24070174e+00,
       -9.00496560e-01, -1.04091877e+00,  1.60144538e-03,  5.81131745e-02,
       -8.78531640e-01, -9.81358814e-01, -9.54708479e-01,  1.09912116e+00,
        1.83686336e-01,  1.09286761e+00,  1.51374547e+00, -1.92558285e+00,
       -7.59368916e-01,  1.07357484e+00,  2.59991483e-01, -7.94804560e-01,
       -1.89996063e+00,  8.31942706e-01, -2.91036197e+00,  1.55480189e+00,
        1.50721575e+00,  1.10778082e-01,  6.43457888e-02, -1.43305327e+00,
       -4.63123049e-02,  1.44773612e+00, -2.62872820e-01, -2.67377762e-01,
        2.03505779e+00, -8.62684313e-01,  1.18879020e-01, -1.19551820e+00,
       -1.08873517e+00, -6.96761007e-01, -1.40214451e+00, -1.10223664e+00,
        2.04718647e+00, -1.18028913e+00, -1.36623662e+00,  1.34380995e+00,
       -1.03316017e+00,  2.03056604e+00, -1.09407196e+00, -6.07667282e-01,
       -1.90610066e+00,  2.27379390e-01, -1.70149472e+00,  2.88184674e-01,
        8.46374982e-01,  2.22671981e+00, -1.33184005e+00, -4.55058633e-01,
       -9.55114786e-01,  7.44981776e-01,  6.71877947e-01,  6.43505438e-01,
       -1.77011663e+00,  2.04185582e+00,  1.86084081e-01,  5.71013737e-01,
        4.91297582e-01,  6.53869400e-01, -1.80178765e-01,  1.46153461e+00,
        2.09772396e+00, -7.48468280e-01, -1.40467547e+00, -1.27330505e+00,
       -3.80897620e-01, -6.87489440e-01, -2.11080778e+00, -1.54278513e+00,
        7.35363602e-01,  4.69253448e-01,  3.11880500e-01, -8.87098732e-01,
       -1.02303758e-01,  6.33282891e-01,  3.86313413e-01,  7.80476447e-01,
       -8.57684115e-02,  8.71250886e-02, -1.14524586e+00,  2.02429259e-01,
       -8.68123055e-01, -2.37132566e-01, -1.59098352e+00,  6.56878717e-01,
        9.51334241e-03, -4.13999793e-01,  2.32380009e+00, -2.55514039e-01,
        1.17610766e-01,  1.52603471e+00, -4.69732093e-01,  1.43447429e+00,
       -1.56266136e+00, -1.69472590e-01, -1.22869797e+00,  4.30838699e-01,
       -2.95975599e-02, -5.82987275e-01,  1.71425049e-01, -3.20759159e-01,
        5.93141864e-01, -1.13519378e+00,  2.19299135e-01,  4.38070497e-01,
       -3.98533291e-01,  1.97508220e+00,  1.99043704e-01,  6.46742248e-01,
       -1.40534208e+00,  7.85283795e-02,  8.57436817e-01,  5.74234059e-01,
       -2.72677148e-01, -4.40667582e-02, -1.23401230e+00,  1.42038973e+00,
       -8.34561047e-01,  7.52597531e-01, -1.37479200e-01,  1.70703854e+00,
       -1.06937709e+00, -5.76633840e-01,  1.04910764e-01, -1.22053187e+00,
        2.24566552e+00,  4.52485220e-01, -2.23680147e+00, -2.00191056e+00,
        2.27151713e-01, -3.66328788e-01, -1.87274850e+00, -1.34047040e+00,
        1.33317516e+00,  2.15833741e-01, -5.96666888e-01,  8.73030235e-01,
        2.65347340e-01,  8.09543598e-01,  1.99727817e+00,  6.83303448e-01,
        1.16724895e+00,  3.45544975e-01,  3.19345287e-02,  9.81851598e-01,
       -3.40053394e-01, -1.05939736e+00, -3.94759115e-01, -8.87876693e-01,
        3.06862224e-01,  4.62780236e-01,  3.67819114e-01,  2.45220424e+00,
        8.13499875e-01,  4.43718573e-01,  5.95025196e-01, -5.28208833e-01,
        2.03526378e-02, -5.00946356e-01, -3.87962243e-01,  2.15824106e+00,
        2.86187567e-01,  1.42582093e+00, -1.25742111e-01,  8.75182771e-01,
       -3.17255535e-01, -3.97457086e-01, -8.22722822e-01,  2.98634295e-01,
       -3.00568057e-02, -2.29521395e-01, -6.85040245e-01,  1.58696450e+00,
       -5.38575713e-01, -1.45025405e+00, -5.07078873e-01, -5.34551912e-01,
        6.95142732e-01,  2.43041056e-01, -1.07979879e+00,  2.09209340e+00,
        1.01256787e+00,  2.83010133e-01, -4.32813245e-01,  3.52360832e-01,
        1.33378178e+00,  6.67183364e-01, -1.02156204e+00,  4.41283444e-01,
        1.11549057e+00, -3.61409422e-01, -1.07530311e+00,  8.96826481e-02,
        4.74542390e-01,  4.02298231e-01,  2.08527411e-01, -9.98671761e-01,
        1.71465515e+00,  4.53791612e-01,  1.02286546e+00,  1.28554293e+00,
       -5.47661938e-01, -1.54977604e+00,  3.30655252e-01,  2.65413921e-01,
       -1.11649694e-02,  7.09720111e-01,  8.01304756e-03, -4.28470893e-01,
        2.31797748e+00, -4.12327118e-01,  9.97087958e-01, -7.63396077e-01,
       -1.69750187e-01, -1.06214870e+00,  1.11478893e+00, -2.36681125e-02,
        2.21626148e+00,  1.38235134e+00,  7.32826035e-01,  7.96474760e-01,
       -1.87536399e+00,  8.01114766e-01,  8.86631169e-01, -1.54405179e-01,
        7.57502399e-01, -4.93117424e-02,  2.90625465e-01,  6.53968041e-01,
       -2.71021140e+00, -1.13230455e+00, -6.43710172e-01, -4.52461804e-01,
       -6.36113287e-01, -1.72045305e+00, -1.54655308e-01,  1.18266942e+00,
        2.18261586e-01,  5.47113968e-02,  4.69101824e-01,  7.04368402e-01,
        2.02557723e+00, -4.84692960e-01, -8.67678167e-01, -4.81805713e-02,
       -2.04013174e+00,  1.56570790e+00,  2.21092011e-01, -2.16530970e-01,
       -6.51314209e-01, -3.06083961e-01, -7.35267113e-03,  1.03288030e+00,
       -1.09558286e+00,  2.27626114e-02, -7.94025713e-01,  9.20691729e-01,
       -5.03213928e-01,  2.93030550e-01,  8.28257657e-01, -5.76448506e-01,
       -7.43203718e-01, -9.45763700e-01,  1.58291520e-01, -7.81633011e-01,
        1.21151669e-01,  8.56257570e-01, -6.23956027e-02, -1.70921117e-01,
       -1.10953326e+00, -9.23124932e-01, -2.93408901e-01,  6.21095369e-01,
       -3.11653695e-01,  4.03087836e-01,  1.92536664e+00, -2.59277695e-01,
        1.05743651e+00, -3.87640604e-01, -9.44058941e-02, -6.34322626e-01,
        1.01127470e+00,  3.04881663e-01, -6.74569508e-01,  6.75079882e-01,
       -1.08819536e+00, -7.16166977e-03,  4.78531998e-02, -4.22557459e-01,
        1.59144872e+00, -5.86325165e-01,  5.80721698e-01, -1.02973482e-01,
        2.77839399e-01, -8.40960765e-01, -2.28822422e-01,  1.12975823e+00,
        2.04146343e-01,  3.12776429e-01,  1.39458331e+00,  4.60306424e-01,
       -1.10018181e+00,  8.83985786e-01, -2.43904498e+00,  1.81394999e-01,
        6.49392693e-01,  1.09463426e+00,  5.86844648e-02, -5.48799701e-02,
        4.89741753e-01, -5.31685880e-01, -5.90600928e-01, -1.37064398e+00,
       -9.75664523e-01, -1.59590852e+00,  3.52095299e-02, -1.29400445e+00,
       -8.69282572e-01,  3.47907449e-01, -1.01204746e-01,  1.16085816e+00,
        5.52143457e-01, -1.41470857e+00,  9.73350623e-01,  4.96442453e-01,
       -7.23823807e-01, -6.94893693e-01, -1.40950000e+00,  1.77560426e+00,
       -6.66613383e-01, -8.18254060e-01, -3.59864465e-01,  1.18176959e-01,
       -1.56473026e+00,  1.08422468e-01, -1.98695525e+00,  3.53916203e-01,
        5.63357685e-01, -8.70545524e-01,  6.40396140e-01, -4.85635753e-01,
       -5.85997423e-01, -8.80647716e-01,  6.51994369e-01,  5.17392690e-01,
       -8.22381406e-01, -9.58334431e-01,  1.65178953e+00, -1.21783021e-01,
        3.76031006e-01,  1.59300741e+00, -1.43113178e-01,  9.24887268e-01,
        1.03147132e+00, -3.10252876e-01,  1.44246721e+00,  6.79641621e-01,
        1.97415484e-01, -4.85018759e-01,  9.54854592e-02,  2.35713305e-01,
        1.12820246e-01, -1.18827073e+00,  2.72572693e-01,  5.16693858e-01,
       -6.72026322e-01, -3.19990034e-01,  8.53602401e-02,  9.93203711e-01,
       -2.26870167e-01, -2.39489850e+00,  2.18293334e-01,  6.74407816e-01,
       -5.35050083e-01,  1.61401619e+00, -6.91394795e-02,  3.90467825e-01,
       -2.12665124e+00,  1.28746878e-01,  1.46610204e-01,  1.40514239e+00,
        1.39175036e+00,  2.06741986e+00, -1.44407913e+00,  1.31618195e+00,
       -8.20927161e-02, -5.98896526e-01,  2.74185777e-01,  1.01784484e+00,
       -1.59161768e+00,  6.78825966e-01,  7.84550641e-01, -9.85674973e-01,
       -4.93364227e-01,  1.05243821e-02,  1.13584475e-01,  6.90112153e-01,
       -9.59577288e-01,  5.69778425e-02,  1.09529008e+00, -5.41096280e-01,
        5.41156133e-01, -7.95884080e-01,  1.10790781e-01,  3.76538349e-01,
       -9.17036863e-01,  1.82067849e+00, -3.00003053e+00,  6.52540620e-01,
       -7.77074359e-01,  5.64163107e-01,  1.52211863e+00, -7.23112037e-01,
        1.97624960e-01,  1.20658547e+00, -1.39270817e+00, -8.71885223e-01,
        4.82683339e-01, -4.10288752e-01,  6.11610774e-01,  7.59055847e-01,
        2.35357883e-03, -4.37374122e-01,  3.89946705e-01,  3.34596341e-01,
       -2.18639142e-01, -1.02357453e+00, -1.49549653e+00,  6.75213293e-01,
       -1.11161047e+00, -3.71836474e-02,  1.21047064e+00, -9.70049037e-01,
        5.33783725e-01,  1.88447480e-01,  2.96958542e-01, -5.87176081e-01,
        2.72611176e-02, -6.56254106e-01,  6.14777385e-01,  4.88537253e-01,
       -6.11827189e-01, -1.21916765e+00, -1.07014241e+00,  4.34514830e-01,
       -2.86145540e-02, -1.56961250e+00, -3.91927898e-01,  1.03318059e+00,
        5.80425222e-02,  2.48027735e-01,  5.23683033e-02,  1.14688085e+00,
        2.69829271e-01,  4.83609693e-01,  8.17028723e-01,  8.48122995e-01,
       -1.75049164e-01, -7.08046559e-01,  3.86784042e-01,  2.35454517e-01,
        7.94628205e-01, -7.74464785e-02,  1.38590394e+00, -7.47298911e-02,
       -1.74602035e+00,  5.23717013e-01, -1.05119518e+00, -8.27872401e-01,
        4.50016740e-01,  8.20077357e-03,  4.21941643e-01, -6.35795314e-01,
       -1.29256553e+00,  6.80531238e-01,  8.05743214e-01,  5.27784676e-01,
        3.13013444e-01,  1.21122916e+00, -1.65658751e+00,  2.36900663e-01,
       -1.10500047e+00,  2.75017592e-01,  1.35883945e+00, -2.77657210e-01,
       -1.73276295e+00, -3.96098706e-01,  7.26862099e-01,  1.79971931e+00,
        8.62813423e-01, -5.73441045e-01,  3.72027111e-01,  4.28740017e-01,
        1.22125920e+00,  8.95215076e-01, -4.69160632e-01, -1.36954827e+00,
        2.44407966e-01,  1.54595287e+00, -6.89059556e-01, -1.87954993e+00,
       -4.90002607e-01, -2.98571288e-02,  4.67618573e-01,  2.95535035e-01,
        7.44060368e-01, -7.18119110e-01,  1.10339019e+00, -9.36089171e-02,
       -1.41993836e+00,  2.68935109e-01, -2.03273474e+00,  2.26973276e+00,
        2.35818068e-01, -1.39045760e-01, -6.26296560e-01,  3.10350655e-01,
        1.60422883e-01,  7.93482475e-01,  9.72222052e-02, -1.09023428e+00,
       -1.08884110e+00,  2.44274648e-01,  1.79530247e+00,  5.34814513e-03,
       -8.21652056e-02,  3.30491050e-01, -2.06955410e+00,  1.53123176e+00,
        1.30169004e-01,  1.18215682e+00,  3.22440725e-01,  1.02201477e-01,
        6.22810628e-01, -7.03147214e-01,  1.35325967e+00, -3.80589737e-01,
        1.20378560e+00,  1.01903655e-01,  6.80838589e-01,  1.00977121e+00,
       -1.29914526e+00, -6.26331469e-02, -1.74073880e+00, -5.05785759e-01,
        5.48464908e-01, -6.19564880e-01, -8.97758521e-01, -3.00127863e+00,
       -1.20008213e+00, -2.28431645e-01,  1.20678377e+00, -1.04934513e+00,
        1.78505959e-01, -3.41376444e-01,  1.07815896e+00,  1.02922909e+00,
       -1.99757226e+00,  4.31862259e-01,  4.61514402e-01,  1.33808770e+00,
       -7.95780314e-03, -7.96765987e-01,  1.04285719e-01,  7.69086011e-01,
        1.06791125e+00,  5.13373646e-01, -1.84511992e-01,  9.64196417e-01,
       -1.40417997e-01,  7.66134857e-01, -5.65177587e-01,  1.43218651e+00,
       -2.77846207e-01,  4.90183101e-01,  9.37942661e-01,  9.03848175e-03,
       -1.02847909e+00, -1.43531525e+00,  4.17198344e-01, -4.20753369e-01,
       -5.75581494e-01, -1.04852857e-01,  1.08776672e+00,  3.35018526e-01,
       -4.94116510e-01,  1.53384284e+00,  9.40218754e-01, -2.87772524e-01,
       -1.83688827e-01,  1.08078522e-01,  3.75637065e-01,  1.18194121e+00,
       -1.22345183e+00, -4.65172860e-01, -4.30742257e-01, -1.45516547e+00,
        1.49963170e+00, -4.85489165e-01, -1.73805444e-01, -8.13176695e-01,
       -1.48679850e-01, -2.39380231e-01, -1.43146206e+00,  3.12351468e-03,
       -2.87584121e-01, -1.18219614e+00,  3.21193815e-01,  3.01676621e-01,
       -4.76827812e-01, -1.59234528e-01, -2.35283408e-01,  1.49044760e+00,
        7.75404719e-01,  4.65781230e-01,  1.28735857e-01,  2.83454168e-02,
       -1.69597229e-01,  7.86883389e-01, -9.27653100e-01,  5.37685433e-01,
        3.80190770e-02, -8.21881489e-02, -1.57537146e+00, -1.69087934e+00,
       -9.78448915e-01, -5.99250602e-01,  2.18738994e+00, -6.05314240e-01])

In [3]:
## CREATE MY DATAFRAME WITH IMBALANCED DATASET
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [4]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [6]:
df.tail()

     feature_1  feature_2  target
995   1.376371   2.845701       1
996   2.239810   0.880077       1
997   1.131760   1.640703       1
998   2.902006   0.390305       1
999   2.697490   2.013570       1

In [7]:
df['target'].value_counts()

0    900
1    100
Name: target, dtype: int64

In [8]:
## upsampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [9]:
from sklearn.utils import resample
df_minority_upsampled=resample(df_minority,replace=True, #Sample With replacement
         n_samples=len(df_majority),
         random_state=42
        )

In [10]:
df_minority_upsampled.shape

(900, 3)

In [11]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [13]:
df_upsampled=pd.concat([df_majority,df_minority_upsampled])

In [14]:
df_upsampled['target'].value_counts()

0    900
1    900
Name: target, dtype: int64

## Down Sampling

In [15]:
import pandas as pd

# Set the random seed for reproducibility
np.random.seed(123)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

df = pd.concat([class_0, class_1]).reset_index(drop=True)

# Check the class distribution
print(df['target'].value_counts())

0    900
1    100
Name: target, dtype: int64

In [16]:
## downsampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [ ]:
from sklearn.utils import resample
df_majority_downsampled=resample(df_majority,replace=False, 
         n_samples=len(df_minority),
         random_state=42
        )